# Generated by Django 5.0.6 on 2024-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furumapp', '0002_alter_post_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('post_count', models.IntegerField()),
            ],
        ),
    ]
