# Generated by Django 5.0.6 on 2024-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furumapp', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
    ]
