# Generated by Django 5.0.6 on 2024-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furumapp', '0006_alter_post_image_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='./static/images/'),
        ),
    ]
