# Generated by Django 4.2.13 on 2024-05-20 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furumapp', '0011_alter_post_text_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 22, 33, 55, 259494)),
        ),
    ]
